### ISSUE TITLE
assert component_version == 0x14 

### ISSUE THREAD

**Issue by dr-apple** [nahueldsanchez/pycc1101#3]
Hi i have this problem:

python rx.py 
Traceback (most recent call last):
  File "rx.py", line 8, in <module>
    ticc1101.selfTest()
  File "/home/pi/pycc1101/pycc1101/pycc1101.py", line 167, in selfTest
    assert component_version == 0x14
AssertionError

What can i do ti fix the problem ?

**Comment by unixb0y** [comment]
Can you do a print(component_version)?
Most probably you have a mistake in your wiring or so.
This is a check to see if everything is configured correctly and it appears not to in your case.

**Comment by nahueldsanchez** [comment]
Hi @dr-apple, as @unixb0y told you, probably there is some problem with the wiring or with the component itself. That assertion is based on the TICC1101 documentation. Can you review how your module it's connected?

**Comment by TIM-PBR** [comment]
> 嗨，我有这个问题：
> 
> 蟒蛇rx.py
> 回溯（最近通话最后一个）：
> 文件“rx.py”，8号线，在
> ticc1101.selfTest（）
> 文件“/home/pi/pycc1101/pycc1101/pycc1101.py”，线路167，在自检
> 断言component_version == 0x14
> AssertionError
> 
> Hello, have you solved this problem? I have the same problem. Thank you

**Comment by eadmaster** [comment]
this happens if you don't connect the pins  correctly
